// a functions definition can directly be implemented with a try-catch block
void function_followed_by_try_catch()
try {
  // useful implementation that may cause exception goes here
} catch(int i) {

}